# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-02 10:04
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.admin import User


def create_superuser(apps, schema_editor):

    if schema_editor.connection.alias == 'dev6gi28djtjfd':
        return

    superuser = User()
    superuser.is_active = True
    superuser.is_superuser = True
    superuser.is_staff = True
    superuser.is_superuser = True
    superuser.username = 'soohtingcoding'
    superuser.email = 'admin@admin.net'
    superuser.set_password('soothingcoding')
    superuser.save()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_superuser)
    ]
