# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-07 07:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180907_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='SnippetExtension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snippets', to='main.SnippetExtension'),
        ),
    ]
