# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-07 07:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180907_0910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='SnippetExtension',
        ),
        migrations.RemoveField(
            model_name='snippetextension',
            name='extended_object',
        ),
        migrations.RemoveField(
            model_name='snippetextension',
            name='public_extension',
        ),
        migrations.DeleteModel(
            name='Snippet',
        ),
        migrations.DeleteModel(
            name='SnippetExtension',
        ),
    ]
