# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-07 07:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippetextension',
            name='page',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='extended_fields', to='cms.Page', unique=True, verbose_name='Page'),
            preserve_default=False,
        ),
    ]
