# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-07 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_remove_snippetextension_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='SnippetExtension',
        ),
        migrations.AddField(
            model_name='snippet',
            name='SnippetExtension',
            field=models.ManyToManyField(related_name='snippets', to='snippets.SnippetExtension'),
        ),
    ]
