# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-11 15:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0005_auto_20180907_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippetextension',
            name='name',
        ),
    ]
