# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-05 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Potential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.CharField(max_length=255)),
                ('project_desc', models.TextField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_company', models.CharField(max_length=255)),
                ('contact_desc', models.TextField()),
            ],
        ),
    ]
