# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-30 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potential',
            name='project_type',
            field=models.CharField(choices=[('SC', 'Site Vitrine'), ('SP', 'E-commerce'), ('MO', 'Maintenance'), ('SEI', 'SEO'), ('U', 'Autre')], max_length=255),
        ),
    ]
