# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-04 07:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0002_auto_20180830_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='potential',
            name='dt_contact',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
